### ISSUE TITLE
delete column customer?

### ISSUE THREAD

**Issue by siandav** [ironhack-edu/data_1.02_excel_activity#16]
if they delete customer id column they cannot do the exercise...

@sandrabosk

**Comment by haggarw3** [comment]
@siandav Can you please point to the resource and the question , so that I can take a look. Thank you Sian :)

**Comment by ironhack-edu** [comment]
@haggarw3 I think Sian is referring to 1.02 - bulletpoint 3: [here](https://github.com/ironhack-edu/data_1.02_excel_activity/blob/master/files_for_activities/tasks.md)

**Comment by Efrainbp** [comment]
@sandrabosk The bullet 3 ¨Deleting and rearranging columns – delete the column customer as it is only a unique identifier for each row of data" will be replace by:

- Keep "Customer" column as the first column in the file
